Custom mode for column templates
Plumsail/forms-docs pull request #80
Opened 2022-11-09 07:53 UTC by mnikitinaa

2022-11-10 09:10 UTC, jusper-dk requested changes

2022-11-10 09:10 UTC, jusper-dk commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
> +    function combinePaths(...paths) {
Вместо этой функции можно просто проверить webUrl:
cosnt webUrl = ctx.webUrl.length > 1 ? ctx.webUrl + '/' : ctx.webUrl

и потом построить formUrl так:
let formUrl = webUrl + \`_layouts/15/listform.aspx?PageType=${4}&ListId=${listId}&ID=${row.ID}\`;

2022-11-10 09:10 UTC, jusper-dk commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
> +.. code-block:: javascript
Тут у меня сломалось форматирование:
![image](https://user-images.githubusercontent.com/27721442/201047782-e6ffb13e-7aee-4cb4-82ec-9cf5242fea65.png)

2022-11-10 09:10 UTC, jusper-dk commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
>  .. code-block:: javascript
Давай этот пример код упростим, покажем только идею:
```

fd.spRendered(function() {
    fd.control('SPDataTable1').templates = {
        // Template for PercentCompleted field
        PercentComplete: function(ctx) {
            // code of your formatter
	    return 'html';
        },
        // Template for AssignedTo field
        AssignedTo: function(ctx) {
            // code of your formatter
	    return 'html';
        },
        TaskDueDate: function(ctx) {
            
        },
        Predecessors: function(ctx) {
		
        }
    }
})
```

2022-11-14 11:30 UTC, mnikitinaa commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
> +    function combinePaths(...paths) {
Эта функция из дизайнера. Это пример для колонки Title. Получается пример тоже можно упростить?

2022-11-16 16:32 UTC, jusper-dk commented
А зачем ты слюда подмешала toggle? Ну в принципе давай закончим тогда один этот PR, но проверь, что все корректно замержилось. Другой PR удаляй тогда.

2022-11-16 16:32 UTC, jusper-dk requested changes

2022-11-16 16:32 UTC, jusper-dk commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
> +    const formUrl = `${baseUrl}/_layouts/15/listform.aspx?PageType=4%26ListId=${listId}%26ID=${row.ID}`;
Почему тут %26, а ниже в такой же строке &?

2022-11-17 06:36 UTC, mnikitinaa commented on SharePoint/designer/controls/list-or-library/list-or-library-columns.rst
> +    const formUrl = `${baseUrl}/_layouts/15/listform.aspx?PageType=4%26ListId=${listId}%26ID=${row.ID}`;
 Потому что в примере с Send e-mail to a user ссылка - часть HTML кода. Если оставить & то параметры ListID и Item ID игнорируются, тк & не правильно кодируется. 
В примере с Copy item link to clipboard это сразу прямая ссылка, поэтому работает c &

> А зачем ты сюда подмешала toggle?
Я всё еще не научилась с несколькими ветками работать. Смешала вчера всё в одну кучу и не разобралась как откатить. Проверила, всё нормально.

2022-11-17 09:52 UTC, merged